var namespacepip_1_1__internal_1_1exceptions =
[
    [ "PipError", "classpip_1_1__internal_1_1exceptions_1_1PipError.html", null ],
    [ "DiagnosticPipError", "classpip_1_1__internal_1_1exceptions_1_1DiagnosticPipError.html", null ],
    [ "ConfigurationError", "classpip_1_1__internal_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "InstallationError", "classpip_1_1__internal_1_1exceptions_1_1InstallationError.html", null ],
    [ "UninstallationError", "classpip_1_1__internal_1_1exceptions_1_1UninstallationError.html", null ],
    [ "MissingPyProjectBuildRequires", "classpip_1_1__internal_1_1exceptions_1_1MissingPyProjectBuildRequires.html", null ],
    [ "InvalidPyProjectBuildRequires", "classpip_1_1__internal_1_1exceptions_1_1InvalidPyProjectBuildRequires.html", null ],
    [ "NoneMetadataError", "classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError.html", "classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError" ],
    [ "UserInstallationInvalid", "classpip_1_1__internal_1_1exceptions_1_1UserInstallationInvalid.html", null ],
    [ "InvalidSchemeCombination", "classpip_1_1__internal_1_1exceptions_1_1InvalidSchemeCombination.html", null ],
    [ "DistributionNotFound", "classpip_1_1__internal_1_1exceptions_1_1DistributionNotFound.html", null ],
    [ "RequirementsFileParseError", "classpip_1_1__internal_1_1exceptions_1_1RequirementsFileParseError.html", null ],
    [ "BestVersionAlreadyInstalled", "classpip_1_1__internal_1_1exceptions_1_1BestVersionAlreadyInstalled.html", null ],
    [ "BadCommand", "classpip_1_1__internal_1_1exceptions_1_1BadCommand.html", null ],
    [ "CommandError", "classpip_1_1__internal_1_1exceptions_1_1CommandError.html", null ],
    [ "PreviousBuildDirError", "classpip_1_1__internal_1_1exceptions_1_1PreviousBuildDirError.html", null ],
    [ "NetworkConnectionError", "classpip_1_1__internal_1_1exceptions_1_1NetworkConnectionError.html", "classpip_1_1__internal_1_1exceptions_1_1NetworkConnectionError" ],
    [ "InvalidWheelFilename", "classpip_1_1__internal_1_1exceptions_1_1InvalidWheelFilename.html", null ],
    [ "UnsupportedWheel", "classpip_1_1__internal_1_1exceptions_1_1UnsupportedWheel.html", null ],
    [ "InvalidWheel", "classpip_1_1__internal_1_1exceptions_1_1InvalidWheel.html", null ],
    [ "MetadataInconsistent", "classpip_1_1__internal_1_1exceptions_1_1MetadataInconsistent.html", null ],
    [ "InstallationSubprocessError", "classpip_1_1__internal_1_1exceptions_1_1InstallationSubprocessError.html", null ],
    [ "MetadataGenerationFailed", "classpip_1_1__internal_1_1exceptions_1_1MetadataGenerationFailed.html", null ],
    [ "HashErrors", "classpip_1_1__internal_1_1exceptions_1_1HashErrors.html", null ],
    [ "HashError", "classpip_1_1__internal_1_1exceptions_1_1HashError.html", "classpip_1_1__internal_1_1exceptions_1_1HashError" ],
    [ "VcsHashUnsupported", "classpip_1_1__internal_1_1exceptions_1_1VcsHashUnsupported.html", null ],
    [ "DirectoryUrlHashUnsupported", "classpip_1_1__internal_1_1exceptions_1_1DirectoryUrlHashUnsupported.html", null ],
    [ "HashMissing", "classpip_1_1__internal_1_1exceptions_1_1HashMissing.html", "classpip_1_1__internal_1_1exceptions_1_1HashMissing" ],
    [ "HashUnpinned", "classpip_1_1__internal_1_1exceptions_1_1HashUnpinned.html", null ],
    [ "HashMismatch", "classpip_1_1__internal_1_1exceptions_1_1HashMismatch.html", "classpip_1_1__internal_1_1exceptions_1_1HashMismatch" ],
    [ "UnsupportedPythonVersion", "classpip_1_1__internal_1_1exceptions_1_1UnsupportedPythonVersion.html", null ],
    [ "ConfigurationFileCouldNotBeLoaded", "classpip_1_1__internal_1_1exceptions_1_1ConfigurationFileCouldNotBeLoaded.html", null ],
    [ "ExternallyManagedEnvironment", "classpip_1_1__internal_1_1exceptions_1_1ExternallyManagedEnvironment.html", null ]
];