var namespaceuvicorn_1_1__types =
[
    [ "ASGIVersions", "classuvicorn_1_1__types_1_1ASGIVersions.html", null ],
    [ "HTTPScope", "classuvicorn_1_1__types_1_1HTTPScope.html", null ],
    [ "WebSocketScope", "classuvicorn_1_1__types_1_1WebSocketScope.html", null ],
    [ "LifespanScope", "classuvicorn_1_1__types_1_1LifespanScope.html", null ],
    [ "HTTPRequestEvent", "classuvicorn_1_1__types_1_1HTTPRequestEvent.html", null ],
    [ "HTTPResponseDebugEvent", "classuvicorn_1_1__types_1_1HTTPResponseDebugEvent.html", null ],
    [ "HTTPResponseStartEvent", "classuvicorn_1_1__types_1_1HTTPResponseStartEvent.html", null ],
    [ "HTTPResponseBodyEvent", "classuvicorn_1_1__types_1_1HTTPResponseBodyEvent.html", null ],
    [ "HTTPResponseTrailersEvent", "classuvicorn_1_1__types_1_1HTTPResponseTrailersEvent.html", null ],
    [ "HTTPServerPushEvent", "classuvicorn_1_1__types_1_1HTTPServerPushEvent.html", null ],
    [ "HTTPDisconnectEvent", "classuvicorn_1_1__types_1_1HTTPDisconnectEvent.html", null ],
    [ "WebSocketConnectEvent", "classuvicorn_1_1__types_1_1WebSocketConnectEvent.html", null ],
    [ "WebSocketAcceptEvent", "classuvicorn_1_1__types_1_1WebSocketAcceptEvent.html", null ],
    [ "_WebSocketReceiveEventBytes", "classuvicorn_1_1__types_1_1__WebSocketReceiveEventBytes.html", null ],
    [ "_WebSocketReceiveEventText", "classuvicorn_1_1__types_1_1__WebSocketReceiveEventText.html", null ],
    [ "_WebSocketSendEventBytes", "classuvicorn_1_1__types_1_1__WebSocketSendEventBytes.html", null ],
    [ "_WebSocketSendEventText", "classuvicorn_1_1__types_1_1__WebSocketSendEventText.html", null ],
    [ "WebSocketResponseStartEvent", "classuvicorn_1_1__types_1_1WebSocketResponseStartEvent.html", null ],
    [ "WebSocketResponseBodyEvent", "classuvicorn_1_1__types_1_1WebSocketResponseBodyEvent.html", null ],
    [ "WebSocketDisconnectEvent", "classuvicorn_1_1__types_1_1WebSocketDisconnectEvent.html", null ],
    [ "WebSocketCloseEvent", "classuvicorn_1_1__types_1_1WebSocketCloseEvent.html", null ],
    [ "LifespanStartupEvent", "classuvicorn_1_1__types_1_1LifespanStartupEvent.html", null ],
    [ "LifespanShutdownEvent", "classuvicorn_1_1__types_1_1LifespanShutdownEvent.html", null ],
    [ "LifespanStartupCompleteEvent", "classuvicorn_1_1__types_1_1LifespanStartupCompleteEvent.html", null ],
    [ "LifespanStartupFailedEvent", "classuvicorn_1_1__types_1_1LifespanStartupFailedEvent.html", null ],
    [ "LifespanShutdownCompleteEvent", "classuvicorn_1_1__types_1_1LifespanShutdownCompleteEvent.html", null ],
    [ "LifespanShutdownFailedEvent", "classuvicorn_1_1__types_1_1LifespanShutdownFailedEvent.html", null ],
    [ "ASGI2Protocol", "classuvicorn_1_1__types_1_1ASGI2Protocol.html", null ]
];