var namespacehttpx_1_1__exceptions =
[
    [ "HTTPError", "classhttpx_1_1__exceptions_1_1HTTPError.html", null ],
    [ "RequestError", "classhttpx_1_1__exceptions_1_1RequestError.html", null ],
    [ "TransportError", "classhttpx_1_1__exceptions_1_1TransportError.html", null ],
    [ "TimeoutException", "classhttpx_1_1__exceptions_1_1TimeoutException.html", null ],
    [ "ConnectTimeout", "classhttpx_1_1__exceptions_1_1ConnectTimeout.html", null ],
    [ "ReadTimeout", "classhttpx_1_1__exceptions_1_1ReadTimeout.html", null ],
    [ "WriteTimeout", "classhttpx_1_1__exceptions_1_1WriteTimeout.html", null ],
    [ "PoolTimeout", "classhttpx_1_1__exceptions_1_1PoolTimeout.html", null ],
    [ "NetworkError", "classhttpx_1_1__exceptions_1_1NetworkError.html", null ],
    [ "ReadError", "classhttpx_1_1__exceptions_1_1ReadError.html", null ],
    [ "WriteError", "classhttpx_1_1__exceptions_1_1WriteError.html", null ],
    [ "ConnectError", "classhttpx_1_1__exceptions_1_1ConnectError.html", null ],
    [ "CloseError", "classhttpx_1_1__exceptions_1_1CloseError.html", null ],
    [ "ProxyError", "classhttpx_1_1__exceptions_1_1ProxyError.html", null ],
    [ "UnsupportedProtocol", "classhttpx_1_1__exceptions_1_1UnsupportedProtocol.html", null ],
    [ "ProtocolError", "classhttpx_1_1__exceptions_1_1ProtocolError.html", null ],
    [ "LocalProtocolError", "classhttpx_1_1__exceptions_1_1LocalProtocolError.html", null ],
    [ "RemoteProtocolError", "classhttpx_1_1__exceptions_1_1RemoteProtocolError.html", null ],
    [ "DecodingError", "classhttpx_1_1__exceptions_1_1DecodingError.html", null ],
    [ "TooManyRedirects", "classhttpx_1_1__exceptions_1_1TooManyRedirects.html", null ],
    [ "HTTPStatusError", "classhttpx_1_1__exceptions_1_1HTTPStatusError.html", null ],
    [ "InvalidURL", "classhttpx_1_1__exceptions_1_1InvalidURL.html", null ],
    [ "CookieConflict", "classhttpx_1_1__exceptions_1_1CookieConflict.html", null ],
    [ "StreamError", "classhttpx_1_1__exceptions_1_1StreamError.html", null ],
    [ "StreamConsumed", "classhttpx_1_1__exceptions_1_1StreamConsumed.html", null ],
    [ "StreamClosed", "classhttpx_1_1__exceptions_1_1StreamClosed.html", null ],
    [ "ResponseNotRead", "classhttpx_1_1__exceptions_1_1ResponseNotRead.html", null ],
    [ "RequestNotRead", "classhttpx_1_1__exceptions_1_1RequestNotRead.html", null ],
    [ "request_context", "namespacehttpx_1_1__exceptions.html#a46d6b496046db78e7e8f334fbb3eb27a", null ]
];